2025-09-27 11:11:29,290 ERROR: Exception on /user/trevor [GET] [in /Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/routes.py", line 75, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/templates/base.html", line 28, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/templates/user.html", line 19, in block 'content'
    {{ form.hidden_tag() }}
    ^^^^^^^^^^^^^^^^^
TypeError: FlaskForm.hidden_tag() missing 1 required positional argument: 'self'
2025-09-30 14:07:46,976 INFO: Microblog startup [in /Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/__init__.py:51]
2025-09-30 14:08:31,502 INFO: Microblog startup [in /Users/trevornance/coding/web_stuff/flask_mega_tutorial-microblog/app/__init__.py:53]
